package manifest

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"universal-manifest-sync-cli/scanner"
)

// AptGenerator creates apt manifest
type AptGenerator struct{}

var pkgToApt = map[string]string{
	"git":    "git",
	"node":   "nodejs",
	"python": "python3",
	"gcc":    "gcc",
	"make":   "make",
	"curl":   "curl",
	"wget":   "wget",
}

var toolToApt = map[string]string{
	"git":     "git",
	"node":    "nodejs",
	"python":  "python3",
	"docker":  "docker.io",
	"kubectl": "kubectl",
}

func (g *AptGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	var sb strings.Builder

	sb.WriteString("# APT manifest generated by Universal Manifest Sync CLI\n")
	sb.WriteString("# Install command:\n")
	sb.WriteString("# sudo apt update && sudo apt install -y <package_names>\n\n")

	// Create a set of packages to install
	pkgSet := make(map[string]struct{})
	for _, pkg := range result.Packages {
		if apt, ok := pkgToApt[pkg.Name]; ok {
			pkgSet[apt] = struct{}{}
		}
	}
	for _, tool := range result.Tools {
		if apt, ok := toolToApt[tool.Name]; ok {
			pkgSet[apt] = struct{}{}
		}
	}
	if len(pkgSet) > 0 {
		// Sort packages for consistent output
		pkgs := make([]string, 0, len(pkgSet))
		for pkg := range pkgSet {
			pkgs = append(pkgs, pkg)
		}
		sort.Strings(pkgs)

		sb.WriteString("sudo apt update\n")
		sb.WriteString("sudo apt install -y \\\n")

		for i, pkg := range pkgs {
			if i == len(pkgs)-1 {
				sb.WriteString(fmt.Sprintf(" %s\n", pkg))
			} else {
				sb.WriteString(fmt.Sprintf("  %s \\\n", pkg))
			}
		}
	}

	// Add comment about apt file format
	sb.WriteString("\n# Alternative: Create a file with package names and use:\n")
	sb.WriteString("# cat packages.txt | xargs sudo apt install -y\n")

	content := sb.String()
	if outputFile != "" {
		return os.WriteFile(outputFile, []byte(content), 0644)
	}
	fmt.Println(content)
	return nil
}
