package manifest

import (
	"fmt"
	"os"
	"strings"

	"universal-manifest-sync-cli/scanner"
)

// BrewGenerator creates Homebrew manifest
type BrewGenerator struct{}

func (g *BrewGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	var sb strings.Builder

	sb.WriteString("# Homebrew manifest generated by Universal Manifest Sync CLI\n")
	sb.WriteString("# Install commands:\n\n")

	// Add packages found in scan results
	if len(result.Packages) > 0 {
		sb.WriteString("# Packages:\n")
		for pkg := range result.Packages {
			sb.WriteString(fmt.Sprintf("brew install %s\n", pkg))
		}
		sb.WriteString("\n")
	}

	// Add tools found in scan results
	// Add tools found in scan results
	if len(result.Tools) > 0 {
		sb.WriteString("# Tools:\n")
		for _, tool := range result.Tools {
			sb.WriteString(fmt.Sprintf("brew install %s\n", tool.Name))
		}
		sb.WriteString("\n")
	}

	// Add cask install commands for GUI applications
	sb.WriteString("# Cask install commands (for GUI applications):\n")
	for _, pkg := range result.Packages { // Iterate over slice elements
		// Common GUI applications that might be installed via cask
		guiApps := map[string]bool{
			"vscode": true,
			"docker": true,
		}
		if guiApps[pkg.Name] { // Access the Name field
			sb.WriteString(fmt.Sprintf("brew install --cask %s\n", pkg.Name))
		}
	}

	content := sb.String()
	if outputFile != "" {
		return os.WriteFile(outputFile, []byte(content), 0644)
	}
	fmt.Println(content)
	return nil
}
