package manifest

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"universal-manifest-sync-cli/scanner"
)

// Generator creates manifest in different formats
type Generator interface {
	Generate(scanResult *scanner.ScanResult, outputFile string) error
}

// DockerGenerator creates Dockerfile
type DockerGenerator struct{}

func (g *DockerGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	var sb strings.Builder
	sb.WriteString("FROM alpine:latest\n\n")
	sb.WriteString("# Generated by Universal Manifest Sync CLI\n\n")

	toolToAlpine := map[string]string{
		"git":    "git",
		"node":   "nodejs",
		"python": "python3",
		"kubectl": "kubectl",
		"helm":   "helm",
		"docker": "docker-cli",
	}

	pkgSet := make(map[string]struct{})
	for name := range result.Packages {
		// Pass through already-normalized generic names; keep as-is for now
		pkgSet[name] = struct{}{}
	}
	for tool := range result.Tools {
		if alpine, ok := toolToAlpine[tool]; ok {
			pkgSet[alpine] = struct{}{}
		}
	}

	if len(pkgSet) > 0 {
		pkgs := make([]string, 0, len(pkgSet))
		for p := range pkgSet {
			pkgs = append(pkgs, p)
		}
		sort.Strings(pkgs)
		sb.WriteString("RUN apk add --no-cache ")
		sb.WriteString(strings.Join(pkgs, " "))
		sb.WriteString("\n")
	}

	sb.WriteString("\nCMD [\"/bin/sh\"]")

	if outputFile != "" {
		return os.WriteFile(outputFile, []byte(sb.String()), 0644)
	}
	fmt.Println(sb.String())
	return nil
}
