package manifest

import (
	"fmt"
	"os"
	"strings"

	"universal-manifest-sync-cli/scanner"
)

// Generator creates manifest in different formats
type Generator interface {
	Generate(scanResult *scanner.ScanResult, outputFile string) error
}

// NewGenerator creates format-specific generator
func NewGenerator(format string) Generator {
	switch format {
	case "docker":
		return &DockerGenerator{}
	case "winget":
		return &WingetGenerator{}
	case "vcpkg":
		return &VcpkgGenerator{}
	case "brew":
		return &BrewGenerator{}
	case "apt":
		return &AptGenerator{}
	case "pip":
		return &PipGenerator{}
	case "npm":
		return &NPMGenerator{}
	default:
		return nil
	}
}

// DockerGenerator creates Dockerfile
type DockerGenerator struct{}

func (g *DockerGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	var sb strings.Builder
	sb.WriteString("FROM alpine:latest\n\n")
	sb.WriteString("# Generated by Universal Manifest Sync CLI\n\n")

	if len(result.Packages) > 0 {
		pkgs := make([]string, 0, len(result.Packages))
		for name := range result.Packages {
			pkgs = append(pkgs, name)
		}
		sb.WriteString("RUN apk add --no-cache ")
		sb.WriteString(strings.Join(pkgs, " "))
		sb.WriteString("\n")
	}

	if len(result.Tools) > 0 {
		sb.WriteString("\n# Install tools\n")
		for tool := range result.Tools {
			sb.WriteString(fmt.Sprintf("RUN wget -O /usr/bin/%s https://example.com/tools/%s && chmod +x /usr/bin/%s\n",
				tool, tool, tool))
		}
	}

	sb.WriteString("\nCMD [\"/bin/sh\"]")

	if outputFile != "" {
		return os.WriteFile(outputFile, []byte(sb.String()), 0644)
	}
	fmt.Println(sb.String())
	return nil
}
