package manifest

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"universal-manifest-sync-cli/scanner"
)

// Generator creates manifest in different formats
type Generator interface {
	Generate(scanResult *scanner.ScanResult, outputFile string) error
}

// NewGenerator creates format-specific generator
func NewGenerator(format string) Generator {
	switch format {
	case "docker":
		return &DockerGenerator{}
	case "apt":
		return &AptGenerator{}
	case "brew":
		return &BrewGenerator{}
	case "npm":
		return &NPMGenerator{}
	case "pip":
		return &PipGenerator{}
	case "vcpkg":
		return &VcpkgGenerator{}
	case "winget":
		return &WingetGenerator{}
	default:
		return nil
	}
}

// DockerGenerator creates Dockerfile
type DockerGenerator struct{}

func (g *DockerGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	var sb strings.Builder
	sb.WriteString("FROM alpine:latest\n\n")
	sb.WriteString("# Generated by Universal Manifest Sync CLI\n\n")

	// Known safe Alpine package mapping for generic tool names
	toolToAlpine := map[string]string{
		"git":     "git",
		"node":    "nodejs",
		"python":  "python3",
		"kubectl": "kubectl",
		"helm":    "helm",
		"docker":  "docker-cli",
	}

	// Optional mapping for normalized package names -> Alpine
	// Only names in this map will be installed; all others are ignored
	pkgToAlpine := map[string]string{
		"git":             "git",
		"node":            "nodejs",
		"nodejs":          "nodejs",
		"python":          "python3",
		"python3":         "python3",
		"kubectl":         "kubectl",
		"helm":            "helm",
		"docker":          "docker-cli",
		"bash":            "bash",
		"curl":            "curl",
		"wget":            "wget",
		"make":            "make",
		"gcc":             "gcc",
		"g++":             "g++",
		"build-base":      "build-base",
		"ca-certificates": "ca-certificates",
		"git-lfs":         "git-lfs",
	}

	pkgSet := make(map[string]struct{})
	for _, pkg := range result.Packages {
		if alpine, ok := pkgToAlpine[pkg.Name]; ok {
			pkgSet[alpine] = struct{}{}
		}
	}
	for _, tool := range result.Tools {
		if alpine, ok := toolToAlpine[tool.Name]; ok {
			pkgSet[alpine] = struct{}{}
		}
	}

	if len(pkgSet) > 0 {
		pkgs := make([]string, 0, len(pkgSet))
		for p := range pkgSet {
			pkgs = append(pkgs, p)
		}
		sort.Strings(pkgs)
		sb.WriteString("RUN apk add --no-cache ")
		sb.WriteString(strings.Join(pkgs, " "))
		sb.WriteString("\n")
	}

	sb.WriteString("\nCMD [\"/bin/sh\"]")

	if outputFile != "" {
		return os.WriteFile(outputFile, []byte(sb.String()), 0644)
	}
	fmt.Println(sb.String())
	return nil
}
