package manifest

import (
	"encoding/json"
	"fmt"
	"os"

	"universal-manifest-sync-cli/scanner"
)

// NPMGenerator creates package.json
type NPMGenerator struct{}

func (g *NPMGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	// Create a basic package.json structure
	pkg := map[string]interface{}{
		"name":         "generated-package",
		"version":      "1.0.0",
		"description":  "Package generated by Universal Manifest Sync CLI",
		"dependencies": make(map[string]string),
	}

	// Map some common packages to npm packages
	// This map defines the npm package name and its desired version
	pkgToNpm := map[string]string{
		"node": "^18.0.0", // Example: if "node" is found in scan, add "node": "^18.0.0" to dependencies
		// Add more mappings as needed
	}

	toolToNpm := map[string]string{
		"npm": "^9.0.0", // Example: if "npm" tool is found, add "npm": "^9.0.0"
		// Add more mappings for tools
	}

	pkgSet := make(map[string]struct{})
	dependencies := pkg["dependencies"].(map[string]string)

	// Add any npm packages found in the scan results
	for _, p := range result.Packages {
		pkgName := p.Name
		if version, ok := pkgToNpm[pkgName]; ok {
			dependencies[pkgName] = version
			pkgSet[pkgName] = struct{}{} // Track unique packages
		}
	}

	// Also check for tools that might be npm packages
	for _, t := range result.Tools {
		toolName := t.Name
		if version, ok := toolToNpm[toolName]; ok {
			// Only add if not already added as a package
			if _, exists := pkgSet[toolName]; !exists {
				dependencies[toolName] = version
			}
		}
	}

	// Only include dependencies if there are any
	if len(dependencies) == 0 {
		delete(pkg, "dependencies")
	}

	content, err := json.MarshalIndent(pkg, "", "  ")
	if err != nil {
		return err
	}

	if outputFile != "" {
		return os.WriteFile(outputFile, content, 0644)
	}
	fmt.Println(string(content))
	return nil
}
