package manifest

import (
	"fmt"
	"os"
	"strings"

	"universal-manifest-sync-cli/scanner"
)

// PipGenerator creates pip requirements
type PipGenerator struct{}

func (g *PipGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	var sb strings.Builder

	sb.WriteString("# Requirements.txt generated by Universal Manifest Sync CLI\n")
	sb.WriteString("# Python packages found in the environment\n\n")

	// Common Python packages mapping
	pkgToPip := map[string]string{
		"python":   "# Python interpreter (typically installed separately)",
		"pip":      "pip",
		"numpy":    "numpy",
		"pandas":   "pandas",
		"requests": "requests",
		"flask":    "flask",
		"django":   "django",
	}

	// Assuming toolToPip is the same as pkgToPip for now
	toolToPip := pkgToPip

	pkgSet := make(map[string]struct{})
	for _, pkg := range result.Packages {
		pkgName := pkg.Name
		if pip, ok := toolToPip[pkgName]; ok && !strings.HasPrefix(pip, "#") {
			pkgSet[pip] = struct{}{}
		} else if strings.Contains(pkgName, "python") || strings.Contains(pkgName, "pip") {
			sb.WriteString(fmt.Sprintf("# %s (may need specific version)\n", pkgName))
		}
	}

	for _, tool := range result.Tools {
		toolName := tool.Name
		if pip, ok := toolToPip[toolName]; ok && !strings.HasPrefix(pip, "#") {
			pkgSet[pip] = struct{}{}
		}
	}

	for pkg := range pkgSet {
		sb.WriteString(fmt.Sprintf("%s\n", pkg))
	}

	content := sb.String()
	if outputFile != "" {
		return os.WriteFile(outputFile, []byte(content), 0644)
	}
	fmt.Println(content)
	return nil
}
