package manifest

import (
	"fmt"
	"os"
	"strings"

	"universal-manifest-sync-cli/scanner"
)

// VcpkgGenerator creates vcpkg manifest
type VcpkgGenerator struct{}

func (g *VcpkgGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	var sb strings.Builder

	sb.WriteString("# Vcpkg manifest generated by Universal Manifest Sync CLI\n")
	sb.WriteString("# vcpkg install commands:\n\n")

	// Add packages found in scan results
	if len(result.Packages) > 0 {
		sb.WriteString("# Packages:\n")
		for _, pkg := range result.Packages {
			sb.WriteString(fmt.Sprintf("vcpkg install %s\n", pkg.Name))
		}
		sb.WriteString("\n")
	}

	// Add tools found in scan results
	if len(result.Tools) > 0 {
		sb.WriteString("# Tools:\n")
		for _, tool := range result.Tools {
			sb.WriteString(fmt.Sprintf("vcpkg install %s\n", tool.Name))
		}
		sb.WriteString("\n")
	}

	// Add comment about vcpkg manifest file format
	sb.WriteString("# Note: For vcpkg manifest mode, create a vcpkg.json file with:\n")
	sb.WriteString("# {\n")
	sb.WriteString("#   \"$schema\": \"https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json\",\n")
	sb.WriteString("#   \"name\": \"your-project-name\",\n")
	sb.WriteString("#   \"version\": \"0.0.1\",\n")
	sb.WriteString("#   \"dependencies\": [\n")

	// List dependencies in vcpkg.json format
	firstDep := true
	for _, pkg := range result.Packages {
		if !firstDep {
			sb.WriteString(",\n")
		}
		sb.WriteString(fmt.Sprintf("    \"%s\"", pkg.Name))
		firstDep = false
	}

	sb.WriteString("\n ]\n")
	sb.WriteString("}\n")

	content := sb.String()
	if outputFile != "" {
		return os.WriteFile(outputFile, []byte(content), 0644)
	}
	fmt.Println(content)
	return nil
}
