package manifest

import (
	"fmt"
	"os"
	"strings"

	"universal-manifest-sync-cli/scanner"
)

// WingetGenerator creates winget manifest
type WingetGenerator struct{}

func (g *WingetGenerator) Generate(result *scanner.ScanResult, outputFile string) error {
	var sb strings.Builder

	// Winget install command format
	sb.WriteString("# Winget manifest generated by Universal Manifest Sync CLI\n")
	sb.WriteString("# Install command:\n")
	sb.WriteString("# winget install --id <PackageId> --accept-package-agreements\n\n")

	if len(result.Packages) > 0 {
		sb.WriteString("# Packages:\n")
		for _, pkg := range result.Packages {
			sb.WriteString(fmt.Sprintf("# %s (Score: %d)\n", pkg.Name, pkg.DevScore))
		}
		sb.WriteString("\n")

		// Generate winget install commands for packages
		sb.WriteString("# Winget install commands:\n")
		for _, pkg := range result.Packages {
			// We need to map the cross-platform names back to winget package IDs
			// This is a basic mapping - in a real implementation, we'd need a more comprehensive mapping
			wingetID := mapToWingetID(pkg.Name)
			if wingetID != "" {
				sb.WriteString(fmt.Sprintf("winget install --id %s --accept-package-agreements\n", wingetID))
			}
		}
	}

	if len(result.Tools) > 0 {
		sb.WriteString("\n# Tools:\n")
		for _, tool := range result.Tools {
			sb.WriteString(fmt.Sprintf("# %s\n", tool.Name))
		}
		sb.WriteString("\n")

		// Generate winget install commands for tools
		sb.WriteString("# Winget install commands for tools:\n")
		for _, tool := range result.Tools {
			wingetID := mapToWingetID(tool.Name)
			if wingetID != "" {
				sb.WriteString(fmt.Sprintf("winget install --id %s --accept-package-agreements\n", wingetID))
			}
		}
	}

	content := sb.String()
	if outputFile != "" {
		return os.WriteFile(outputFile, []byte(content), 0644)
	}
	fmt.Println(content)
	return nil
}

// mapToWingetID maps cross-platform package names to winget package IDs
func mapToWingetID(name string) string {
	// Reverse mapping from the Windows scanner mappings
	mapping := map[string]string{
		"git":     "Git.Git",
		"node":    "OpenJS.NodeJS",
		"python":  "Python.Python.3",
		"docker":  "Docker.DockerDesktop",
		"kubectl": "Kubernetes.kubectl",
		"helm":    "Helm.Helm",
		"vscode":  "Microsoft.VisualStudioCode",
		"openjdk": "OpenJDK.OpenJDK",
	}

	if id, exists := mapping[name]; exists {
		return id
	}

	// If no mapping exists, return empty string
	// In a production implementation, you might want to search for packages or return the name as-is
	return ""
}
